#https://learncloudnative.com/blog/2021-07-10-pods-replicasets
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service-loadbalancing
  namespace: demo
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer