apiVersion: v1
kind: Pod
metadata:
  name: load-generator
  namespace: demo
spec:
  containers:
    - name: busybox
      image: busybox
      args:
        - /bin/sh
        - -c
        - |
          while true; do wget -q -O- http://NODE_IP_ADDRESS:8080; done