name: Build Docker Image
on:
  push:
    branches:
      - main
jobs:
  build:
    name: push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build the docker image
        id: build-docker-image
        run: |
          ls -la 
          docker build . -f Dockerfile -t gjj.yulinmei.cn:10443/demo-image-test:latest
      - name: push the docker image
        id: push-docker-image
        run: docker push livekit.yulinmei.cn:10443/demo-image-test:latest
