name: Build Docker Image
on:
  push:
    branches:
      - main
jobs:
  build:
    name: push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build the docker image
        id: build-docker-image
        run: |
          ls -la 
          docker build . -f Dockerfile -t livekit.yulinmei.cn:10443/demo-image-test:latest
      - name: push the docker image
        id: push-docker-image
        run: docker push livekit.yulinmei.cn:10443/demo-image-test:latest
      - name: Creating a Pod
        run: |
          kubectl apply -f .github/hello-world-pod.yaml
      #      - name: Deploying the Application
      #        run: |
      #          kubectl apply -f .github/hello-world-deployment.yaml
      #
      #      - name: Service
      #        run: |
      #          kubectl apply -f .github/service.yml -n nginx --insecure-skip-tls-verify

#      - name: Exposing the Application
#        run: |
#          kubectl expose deployment hello-world --type=ClusterIP --name=hello-world-service --port=8080 --target-port=8080 -n demo




